# Generated by Django 4.1.2 on 2022-10-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correoElectronico', models.CharField(max_length=255)),
                ('fechaIngreso', models.DateField()),
            ],
        ),
    ]
